EGG_GROUPS = {
  "monster": 1,
  "water1": 2,
  "bug": 3,
  "flying": 4,
  "ground": 5,
  "fairy": 6,
  "plant": 7,
  "humanshape": 8,
  "water3": 9,
  "mineral": 10,
  "indeterminate": 11,
  "water2": 12,
  "ditto": 13,
  "dragon": 14,
  "no-eggs": 15,
}

GENDER_RATIOS = {
  -1: 255,
  0: 0,
  1: 31,
  2: 63,
  4: 127,
  6: 191,
  7: 225,
  8: 254,
}

START_OF_LINE_FORMS = {
  "hisuian": "hisui",
  "galarian": "galar",
  "alolan": "alola",
  "paldean": "paldea",
  "gigantamax": "gmax",
  "ash-": "ash ",
  "-f": "-female",
  "drive ": "",
  "type ": " ",
  " strawberry sweet": "",
  " berry sweet": "",
  " love sweet": "",
  " star sweet": "",
  " clover sweet": "",
  " flower sweet": "",
  " ribbon sweet": "",
  " forme power construct": "",
  " rider": "",
  " wings": "",
  " mane ": " ",
  " color": "",
}

END_OF_LINE_FORMS = {
  "forme": "",
  "form": "",
  "pattern": "",
  "mode": "",
  "flower": "",
  "trim": "",
  "size": "",
  "style": "",
  "core": "",
  "face": "",
  "construct": "",
  "sword": "",
  "shield": "",
}

REVERSE_ORDER_ARRAY = [
  "hisui",
  "galar",
  "alola",
  "paldea",
  "mega",
  "gmax",
  "totem",
  "eternamax",
  "dada",
  "ice",
  "white",
  "black",
  "ultra",
  "ash",
  "titanic",
  "shadow",
  "dawn",
  "dusk",
  "original",
]

EXCEPTION_IDS = [
  957,
  958,
  959,
  979,
  980,
  981,
  982,
  983,
  1011,
  1018,
  1019,
]

API_NAME_KEY = {
  "nidoran-female" : "nidoran-f",
  "a-form-unown" : "unown",
  "deoxys" : "deoxys-normal",
  "burmy" : "burmy",
  "wormadam" : "wormadam-plant",
  "cherrim" : "cherrim",
  "shellos" : "shellos",
  "gastrodon" : "gastrodon",
  "giratina" : "giratina-altered",
  "shaymin" : "shaymin-land",
  "arceus" : "arceus",
  "basculin" : "basculin-red-striped",
  "darmanitan" : "darmanitan-standard",
  "deerling" : "deerling",
  "sawsbuck" : "sawsbuck",
  "tornadus" : "tornadus-incarnate",
  "thundurus" : "thundurus-incarnate",
  "landorus" : "landorus-incarnate",
  "keldeo" : "keldeo-ordinary",
  "meloetta" : "meloetta-aria",
  "scatterbug" : "scatterbug",
  "spewpa" : "spewpa",
  "vivillon" : "vivillon",
  "flabebe" : "flabebe",
  "floette" : "floette",
  "florges" : "florges",
  "furfrou" : "furfrou",
  "meowstic" : "meowstic-male",
  "aegislash" : "aegislash-shield",
  "pumpkaboo" : "pumpkaboo-average",
  "gourgeist" : "gourgeist-average",
  "xerneas" : "xerneas",
  "zygarde" : "zygarde-50",
  "oricorio" : "oricorio-baile",
  "lycanroc" : "lycanroc-midday",
  "wishiwashi" : "wishiwashi-solo",
  "-null" : "",
  "silvally" : "silvally",
  "minior" : "minior-red-meteor",
  "mimikyu" : "mimikyu-disguised",
  "toxtricity" : "toxtricity-amped",
  "sinistea" : "sinistea",
  "polteageist" : "polteageist",
  "alcremie" : "alcremie",
  "eiscue" : "eiscue-ice",
  "indeedee" : "indeedee-male",
  "morpeko" : "morpeko-full-belly",
  "urshifu" : "urshifu-single-strike",
  "basculegion" : "basculegion-male",
  "enamorus" : "enamorus-incarnate",
  "dudunsparce" : "dudunsparce-two-segment",
  "three-segment-form-dudunsparce" : "dudunsparce-three-segment",
  "clone-venusaur" : "venusaur",
  "mega-charizard-x" : "charizard-mega-x",
  "mega-charizard-y" : "charizard-mega-y",
  "clone-charizard" : "charizard",
  "clone-blastoise" : "blastoise",
  "totem-alola-raticate" : "raticate-totem-alola",
  "cosplay-pikachu" : "pikachu-cosplay",
  "cosplay-rock-star-pikachu" : "pikachu-rock-star",
  "cosplay-belle-pikachu" : "pikachu-belle",
  "cosplay-pop-star-pikachu" : "pikachu-pop-star",
  "cosplay-phd-pikachu" : "pikachu-phd",
  "cosplay-libre-pikachu" : "pikachu-libre",
  "original-cap-pikachu" : "pikachu-original-cap",
  "hoenn-cap-pikachu" : "pikachu-hoenn-cap",
  "sinnoh-cap-pikachu" : "pikachu-sinnoh-cap",
  "unova-cap-pikachu" : "pikachu-unova-cap",
  "kalos-cap-pikachu" : "pikachu-kalos-cap",
  "alola-cap-pikachu" : "pikachu-alola-cap",
  "partner-cap-pikachu" : "pikachu-partner-cap",
  "world-cap-pikachu" : "pikachu-world-cap",
  "partner-pikachu" : "pikachu-starter",
  "clone-pikachu" : "pikachu",
  "frenzied-lord-of-the-isles-hisui-arcanine" : "arcanine-hisui",
  "haunter-ghost" : "haunter",
  "stitched-gengar" : "gengar",
  "crystal-onix" : "onix",
  "frenzied-lord-of-the-hollow-hisui-electrode" : "electrode-hisui",
  "totem-alola-marowak" : "marowak-totem",
  "galar-mr-mime" : "mr-mime-galar",
  "combat-breed-tauros" : "tauros-paldea-combat-breed",
  "blaze-breed-tauros" : "tauros-paldea-blaze-breed",
  "aqua-breed-tauros" : "tauros-paldea-aqua-breed",
  "partner-eevee" : "eevee-starter",
  "bandana-partner-eevee" : "eevee-starter",
  "kabutops-missingno" : "kabutops",
  "mega-mewtwo-x" : "mewtwo-mega-x",
  "mega-mewtwo-y" : "mewtwo-mega-y",
  "mk-ii-armored-mewtwo" : "mewtwo",
  "mk-i-armored-mewtwo" : "mewtwo",
  "mewtwo-shadow" : "mewtwo",
  "spiky-eared-pichu" : "pichu",
  "b-form-unown" : "unown",
  "c-form-unown" : "unown",
  "d-form-unown" : "unown",
  "e-form-unown" : "unown",
  "f-form-unown" : "unown",
  "g-form-unown" : "unown",
  "h-form-unown" : "unown",
  "i-form-unown" : "unown",
  "j-form-unown" : "unown",
  "k-form-unown" : "unown",
  "l-form-unown" : "unown",
  "m-form-unown" : "unown",
  "n-form-unown" : "unown",
  "o-form-unown" : "unown",
  "p-form-unown" : "unown",
  "q-form-unown" : "unown",
  "r-form-unown" : "unown",
  "s-form-unown" : "unown",
  "t-form-unown" : "unown",
  "u-form-unown" : "unown",
  "v-form-unown" : "unown",
  "w-form-unown" : "unown",
  "x-form-unown" : "unown",
  "y-form-unown" : "unown",
  "z-form-unown" : "unown",
  "e-mark-form-unown" : "unown",
  "q-mark-form-unown" : "unown",
  "lugia-shadow" : "lugia",
  "sunny-form-castform" : "castform-sunny",
  "rainy-form-castform" : "castform-rainy",
  "snowy-form-castform" : "castform-snowy",
  "primal-kyogre" : "kyogre-primal",
  "primal-groudon" : "groudon-primal",
  "meta-groudon" : "groudon",
  "boss-meta-groudon" : "groudon",
  "illusory-rayquaza" : "rayquaza",
  "attack-forme-deoxys" : "deoxys-attack",
  "defense-forme-deoxys" : "deoxys-defense",
  "speed-forme-deoxys" : "deoxys-speed",
  "sandy-cloak-burmy" : "burmy",
  "trash-cloak-burmy" : "burmy",
  "sandy-cloak-wormadam" : "wormadam-sandy",
  "trash-cloak-wormadam" : "wormadam-trash",
  "sunshine-form-cherrim" : "cherrim",
  "east-sea-shellos" : "shellos",
  "east-sea-gastrodon" : "gastrodon",
  "heat-rotom" : "rotom-heat",
  "wash-rotom" : "rotom-wash",
  "frost-rotom" : "rotom-frost",
  "fan-rotom" : "rotom-fan",
  "mow-rotom" : "rotom-mow",
  "origin-forme-dialga" : "dialga-origin",
  "origin-forme-palkia" : "palkia-origin",
  "origin-forme-giratina" : "giratina-origin",
  "sky-forme-shaymin" : "shaymin-sky",
  "fist-plate-arceus" : "arceus",
  "sky-plate-arceus" : "arceus",
  "toxic-plate-arceus" : "arceus",
  "earth-plate-arceus" : "arceus",
  "stone-plate-arceus" : "arceus",
  "insect-plate-arceus" : "arceus",
  "spooky-plate-arceus" : "arceus",
  "iron-plate-arceus" : "arceus",
  "flame-plate-arceus" : "arceus",
  "splash-plate-arceus" : "arceus",
  "meadow-plate-arceus" : "arceus",
  "zap-plate-arceus" : "arceus",
  "mind-plate-arceus" : "arceus",
  "icicle-plate-arceus" : "arceus",
  "draco-plate-arceus" : "arceus",
  "dread-plate-arceus" : "arceus",
  "pixie-plate-arceus" : "arceus",
  "frenzied-lady-of-the-ridge-hisui-lilligant" : "lilligant-hisui",
  "blue-striped-form-basculin" : "basculin-blue-striped",
  "white-striped-form-basculin" : "basculin-white-striped",
  "zen-mode-darmanitan" : "darmanitan-zen",
  "galar-standard-mode-darmanitan" : "darmanitan-galar-standard",
  "galar-zen-mode-darmanitan" : "darmanitan-galar-zen",
  "summer-form-deerling" : "deerling",
  "autumn-form-deerling" : "deerling",
  "winter-form-deerling" : "deerling",
  "summer-form-sawsbuck" : "sawsbuck",
  "autumn-form-sawsbuck" : "sawsbuck",
  "winter-form-sawsbuck" : "sawsbuck",
  "therian-forme-tornadus" : "tornadus-therian",
  "therian-forme-thundurus" : "thundurus-therian",
  "therian-forme-landorus" : "landorus-therian",
  "resolute-form-keldeo" : "keldeo-resolute",
  "pirouette-forme-meloetta" : "meloetta-pirouette",
  "battle-bond-greninja" : "greninja-battle-bond",
  "polar-pattern-vivillon" : "vivillon",
  "tundra-pattern-vivillon" : "vivillon",
  "continental-pattern-vivillon" : "vivillon",
  "garden-pattern-vivillon" : "vivillon",
  "elegant-pattern-vivillon" : "vivillon",
  "meadow-pattern-vivillon" : "vivillon",
  "modern-pattern-vivillon" : "vivillon",
  "marine-pattern-vivillon" : "vivillon",
  "archipelago-pattern-vivillon" : "vivillon",
  "high-plains-pattern-vivillon" : "vivillon",
  "sandstorm-pattern-vivillon" : "vivillon",
  "river-pattern-vivillon" : "vivillon",
  "monsoon-pattern-vivillon" : "vivillon",
  "savanna-pattern-vivillon" : "vivillon",
  "sun-pattern-vivillon" : "vivillon",
  "ocean-pattern-vivillon" : "vivillon",
  "jungle-pattern-vivillon" : "vivillon",
  "fancy-pattern-vivillon" : "vivillon",
  "poke-ball-pattern-vivillon" : "vivillon",
  "yellow-flower-flabebe" : "flabebe",
  "orange-flower-flabebe" : "flabebe",
  "blue-flower-flabebe" : "flabebe",
  "white-flower-flabebe" : "flabebe",
  "yellow-flower-floette" : "floette",
  "orange-flower-floette" : "floette",
  "blue-flower-floette" : "floette",
  "white-flower-floette" : "floette",
  "eternal-flower-floette" : "floette-eternal",
  "yellow-flower-florges" : "florges",
  "orange-flower-florges" : "florges",
  "blue-flower-florges" : "florges",
  "white-flower-florges" : "florges",
  "heart-trim-furfrou" : "furfrou",
  "star-trim-furfrou" : "furfrou",
  "diamond-trim-furfrou" : "furfrou",
  "debutante-trim-furfrou" : "furfrou",
  "matron-trim-furfrou" : "furfrou",
  "dandy-trim-furfrou" : "furfrou",
  "la-reine-trim-furfrou" : "furfrou",
  "pharaoh-trim-furfrou" : "furfrou",
  "female-meowstic" : "meowstic-female",
  "blade-forme-aegislash" : "aegislash-blade",
  "small-size-pumpkaboo" : "pumpkaboo-small",
  "large-size-pumpkaboo" : "pumpkaboo-large",
  "super-size-pumpkaboo" : "pumpkaboo-super",
  "small-size-gourgeist" : "gourgeist-small",
  "large-size-gourgeist" : "gourgeist-large",
  "super-size-gourgeist" : "gourgeist-super",
  "frenzied-lord-of-the-tundra-hisui-avalugg" : "avalugg-hisui",
  "active-mode-xerneas" : "xerneas",
  "zygarde-10-power" : "zygarde-10-power-construct",
  "zygarde-50-power" : "zygarde-50-power-construct",
  "pom-pom-style-oricorio" : "oricorio-pom-pom",
  "pau-style-oricorio" : "oricorio-pau",
  "own-tempo-rockruff" : "rockruff-own-tempo",
  "midnight-form-lycanroc" : "lycanroc-midnight",
  "dusk-form-lycanroc" : "lycanroc-dusk",
  "school-form-wishiwashi" : "wishiwashi-school",
  "totem-solo-form-wishiwashi" : "wishiwashi-solo",
  "totem-school-form-wishiwashi" : "wishiwashi-school",
  "orange-meteor-form-minior" : "minior-orange-meteor",
  "yellow-meteor-form-minior" : "minior-yellow-meteor",
  "green-meteor-form-minior" : "minior-green-meteor",
  "blue-meteor-form-minior" : "minior-blue-meteor",
  "indigo-meteor-form-minior" : "minior-indigo-meteor",
  "violet-meteor-form-minior" : "minior-violet-meteor",
  "red-core-minior" : "minior-red",
  "orange-core-minior" : "minior-orange",
  "yellow-core-minior" : "minior-yellow",
  "green-core-minior" : "minior-green",
  "blue-core-minior" : "minior-blue",
  "indigo-core-minior" : "minior-indigo",
  "violet-core-minior" : "minior-violet",
  "busted-form-mimikyu" : "mimikyu-busted",
  "gulping-form-cramorant" : "cramorant-gulping",
  "gorging-form-cramorant" : "cramorant-gorging",
  "low-key-form-toxtricity" : "toxtricity-low-key",
  "gmax-amped-form-toxtricity" : "toxtricity-amped",
  "gmax-low-key-form-toxtricity" : "toxtricity-low-key",
  "antique-form-sinistea" : "sinistea",
  "antique-form-polteageist" : "polteageist",
  "matcha-cream-alcremie": "alcremie",
  "mint-cream-alcremie": "alcremie",
  "lemon-cream-alcremie": "alcremie",
  "salted-cream-alcremie": "alcremie",
  "ruby-swirl-alcremie": "alcremie",
  "caramel-swirl-alcremie": "alcremie",
  "rainbow-swirl-alcremie": "alcremie",
  "noice-face-eiscue" : "eiscue-noice",
  "female-indeedee" : "indeedee-female",
  "hangry-mode-morpeko" : "morpeko-hangry",
  "crowned-sword-zacian" : "zacian-crowned",
  "crowned-shield-zamazenta" : "zamazenta-crowned",
  "rapid-strike-style-urshifu" : "urshifu-rapid-strike",
  "gmax-single-strike-style-urshifu" : "urshifu-single-strike",
  "gmax-rapid-strike-style-urshifu" : "urshifu-rapid-strike",
  "bloodmoon-beast-ursaluna" : "ursaluna-bloodmoon",
  "female-basculegion" : "basculegion-female",
  "therian-forme-enamorus" : "enamorus-therian",
  "female-oinkologne" : "oinkologne-female",
  "family-of-three-maushold" : "maushold-family-of-three",
  "blue-plumage-squawkabilly" : "squawkabilly-blue-plumage",
  "yellow-plumage-squawkabilly" : "squawkabilly-yellow-plumage",
  "white-plumage-squawkabilly" : "squawkabilly-white-plumage",
  "stony-cliff-titan-klawf" : "klawf",
  "open-sky-titan-bombirdier" : "bombirdier",
}