EGG_GROUPS = {
  "monster": 1,
  "water1": 2,
  "bug": 3,
  "flying": 4,
  "ground": 5,
  "fairy": 6,
  "plant": 7,
  "humanshape": 8,
  "water3": 9,
  "mineral": 10,
  "indeterminate": 11,
  "water2": 12,
  "ditto": 13,
  "dragon": 14,
  "no-eggs": 15,
}

GENDER_RATIOS = {
  -1: 255,
  0: 0,
  1: 31,
  2: 63,
  4: 127,
  6: 191,
  7: 225,
  8: 254,
}

START_OF_LINE_FORMS = {
  "hisuian": "hisui",
  "galarian": "galar",
  "alolan": "alola",
  "paldean": "paldea",
  "gigantamax": "gmax",
  "ash-": "ash ",
  "-f": "-female",
  "drive ": "",
  "type": "",
  " strawberry sweet": "",
  " berry sweet": "",
  " love sweet": "",
  " star sweet": "",
  " clover sweet": "",
  " flower sweet": "",
  " ribbon sweet": "",
  " forme power construct": "",
  " rider": "",
  " wings": "",
  " mane": "",
  " color": "",
}

END_OF_LINE_FORMS = {
  "forme": "",
  "form": "",
  "pattern": "",
  "mode": "",
  "flower": "",
  "trim": "",
  "size": "",
  "style": "",
  "core": "",
  "face": "",
  "construct": "",
  "sword": "",
  "shield": "",
}

REVERSE_ORDER_ARRAY = [
  "hisui",
  "galar",
  "alola",
  "paldea",
  "mega",
  "gmax",
  "totem",
  "eternamax",
  "dada",
  "ice",
  "white",
  "black",
  "ultra",
  "ash",
  "titanic",
  "shadow",
  "dawn",
  "dusk",
  "original",
]
