name: Send updates to dependent repo

on:
  push:
    branches: 
      - main

jobs:
  update-tracker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run 2.0 Convert Python Script
      run: python3 Python_tasks/convert_lmpt_data.py 2.0

    - name: Run 2.0 Tracker Data Script
      run: python3 Python_tasks/trainerDocsUtils.py 2.0

    - name: Run 2.0 Pokedex Script
      run: python3 Python_tasks/pokedex_generator.py 2.0

    - name: Pushes Input Files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_GAMEDATA_AUTOMATION_TOKEN }}
      with:
        source_file: 'input/.'
        destination_branch: 'master'
        destination_repo: 'TeamLumi/LumiPlat_NuzlockeTracker'
        destination_folder: './src/lumi-calc/input'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 2.0 gamedata files'

    - name: Pushes test files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_GAMEDATA_AUTOMATION_TOKEN }}
      with:
        source_file: 'Python_tasks/output/.'
        destination_branch: 'master'
        destination_repo: 'TeamLumi/LumiPlat_NuzlockeTracker'
        destination_folder: './src/constants/generated_files'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 2.0 output files'

  update-lumibot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run 2.0 Pokedex Script
      run: python3 Python_tasks/pokedex_generator.py 2.0

    - name: Pushes test file
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: 'input/.'
        destination_branch: 'master'
        destination_repo: 'TeamLumi/Lumibot'
        destination_folder: './__gamedata'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 2.0 gamedata files'

    - name: Pushes 3.0 test file
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: '3.0Input/.'
        destination_branch: 'master'
        destination_repo: 'TeamLumi/Lumibot'
        destination_folder: './__3.0gamedata'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 3.0 gamedata files'
  
  update-website-main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Vanilla Pokedex Script
      run: python3 Python_tasks/pokedex_generator.py vanilla

    - name: Run Vanilla Trainer Data Script
      run: python3 Python_tasks/trainerDocsUtils.py vanilla

    - name: Run Vanilla Pokemon Location Script
      run: python3 Python_tasks/convert_lmpt_data.py vanilla

    - name: Run 2.0 Pokedex Script
      run: python3 Python_tasks/pokedex_generator.py 2.0

    - name: Run 2.0 Trainer Data Script
      run: python3 Python_tasks/trainerDocsUtils.py 2.0

    - name: Run 2.0 Pokemon Location Script
      run: python3 Python_tasks/convert_lmpt_data.py 2.0

    - name: Run 3.0 Pokedex Script
      run: python3 Python_tasks/pokedex_generator.py 3.0

    - name: Run 3.0 Pokemon Location Script
      run: python3 Python_tasks/convert_lmpt_data.py 3.0

    - name: Update Vanilla gamedata files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: 'vanilla_input/.'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team'
        destination_folder: './__gamedata/gamedataVanilla'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating Vanilla gamedata files'

    - name: Update Vanilla Trainer Files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: 'Python_tasks/outputVanilla/Mapper_Trainer_Output.json'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team'
        destination_folder: './__gamedata/gamedataVanilla'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating Vanilla Trainer files'

    - name: Update 2.0 gamedata files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: 'input/.'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team'
        destination_folder: './__gamedata/gamedata2.0'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 2.0 gamedata files'

    - name: Update 2.0 Trainer Files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: 'Python_tasks/output/Mapper_Trainer_Output.json'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team'
        destination_folder: './__gamedata/gamedata2.0'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 2.0 Trainer files'

    - name: Update 3.0 gamedata files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: '3.0Input/.'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team'
        destination_folder: './__gamedata/gamedata3.0'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 3.0 gamedata files'

  update-dev-website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Vanilla Pokedex Script
      run: python3 Python_tasks/pokedex_generator.py vanilla

    - name: Run Vanilla Trainer Data Script
      run: python3 Python_tasks/trainerDocsUtils.py vanilla

    - name: Run Vanilla Pokemon Location Script
      run: python3 Python_tasks/convert_lmpt_data.py vanilla

    - name: Run 2.0 Pokedex Script
      run: python3 Python_tasks/pokedex_generator.py 2.0

    - name: Run Lumi Data Scripts
      run: python3 Python_tasks/convert_lmpt_data.py 2.0
      
    - name: Run 2.0 Trainer Data Script
      run: python3 Python_tasks/trainerDocsUtils.py 2.0

    - name: Run 3.0 Pokedex Script
      run: python3 Python_tasks/pokedex_generator.py 3.0

    - name: Run 3.0 Trainer Data Script
      run: python3 Python_tasks/trainerDocsUtils.py 3.0

    - name: Run 3.0 Pokemon Location Script
      run: python3 Python_tasks/convert_lmpt_data.py 3.0

    - name: Update Vanilla gamedata files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: 'vanilla_input/.'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team-dev'
        destination_folder: './__gamedata/gamedataVanilla'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating Vanilla gamedata files'

    - name: Update Vanilla Trainer Files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: 'Python_tasks/outputVanilla/Mapper_Trainer_Output.json'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team-dev'
        destination_folder: './__gamedata/gamedataVanilla'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating Vanilla Trainer files'

    - name: Pushes test file
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: 'input/.'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team-dev'
        destination_folder: './__gamedata/gamedata2.0'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 2.0 gamedata files'

    - name: Pushes test files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: 'Python_tasks/output/Mapper_Trainer_Output.json'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team-dev'
        destination_folder: './__gamedata/gamedata2.0'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 2.0 Trainer files'

    - name: Update 3.0 gamedata files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: '3.0Input/.'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team'
        destination_folder: './__gamedata/gamedata3.0'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 3.0 gamedata files'
  
    - name: Update 3.0 Trainer Files
      uses: TeamLumi/Gamedata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DENMARK_LUMIBOT_TOKEN }}
      with:
        source_file: 'Python_tasks/3.0Output/Mapper_Trainer_Output.json'
        destination_branch: 'main'
        destination_repo: 'TeamLumi/luminescent-team-dev'
        destination_folder: './__gamedata/gamedata3.0'
        user_email: '<support+actions@github.com>'
        user_name: 'github-actions-bot'
        commit_message: 'Updating 3.0 Trainer files'
